stages:
  data_ingestion:
    cmd: uv run src/nextWordPrediction/pipeline/data_ingestion_pipeline.py
    deps:
      - src/nextWordPrediction/components/data_ingestion.py
      - config/config.yaml
    outs:
      - artifact/data_ingestion/1661-0.txt
    
  data_transformation:
    cmd: uv run src/nextWordPrediction/pipeline/data_transformation_pipeline.py
    deps:
      - src/nextWordPrediction/components/data_transformation.py
      - config/config.yaml
      - artifact/data_ingestion/1661-0.txt
    outs:
      - artifact/data_transformation/tokenizer.pkl
  
  model_building:
    cmd: uv run src/nextWordPrediction/pipeline/model_building_pipeline.py
    deps:
      - src/nextWordPrediction/components/training_model.py
      - config/config.yaml
      - artifact/data_transformation/train.txt
      - artifact/data_transformation/val.txt
    outs:
      - artifact/build_model/model.pth
    
  model_eval:
    cmd: uv run src/nextWordPrediction/pipeline/model_eval_pipeline.py
    deps:
      - src/nextWordPrediction/components/model_eval.py
      - artifact/data_transformation/test.txt
      - config/config.yaml
      - artifact/build_model/model.pth
    metrics:
      - artifact/model_eval/metric.json:
          cache: false
    